name: build
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B package
    - name: Login to Docker Hub
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: v0.10.0
    - name: Build linux/amd64 image
      run: |
        docker buildx build --push --platform linux/amd64 -f Dockerfile -t manorrock/persian:amd64-latest .
    - name: Build linux/arm64 image
      run: |
        docker buildx build --push --platform linux/arm64 -f Dockerfile.arm64 -t manorrock/persian:arm64-latest .
    - name: Build multi-arch manifest
      run: |
        export DOCKER_CLI_EXPERIMENTAL=enabled
        docker pull manorrock/persian:amd64-latest
        docker pull manorrock/persian:arm64-latest
        docker manifest create manorrock/persian:latest \
           manorrock/persian:amd64-latest \
           manorrock/persian:arm64-latest
        docker manifest annotate manorrock/persian:latest \
           manorrock/persian:amd64-latest --os linux --arch amd64
        docker manifest annotate manorrock/persian:latest \
           manorrock/persian:arm64-latest --os linux --arch arm64
        docker manifest push manorrock/persian:latest
