name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build with Maven
      run: mvn -B package
    - name: Login to Docker Hub
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build container images
      run: |
        docker build -f Dockerfile.amd64 -t manorrock/persian:amd64-latest .
        docker push manorrock/persian:amd64-latest
        export DOCKER_CLI_EXPERIMENTAL=enabled
        docker manifest create manorrock/persian:latest \
           manorrock/persian:amd64-latest
        docker manifest annotate manorrock/persian:latest \
           manorrock/persian:amd64-latest --os linux --arch amd64
        docker manifest push manorrock/persian:latest
