name: release
on:
  push:
    tags:        
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v1
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B -DskipTests=true -f pom.xml install
    - name: Login to Docker Hub
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build container image
      run: |
        TAG=${GITHUB_REF}
        INDEX=${TAG%v*}
        VERSION=${TAG:${#INDEX}}
        docker buildx build --push --platform linux/amd64 -f Dockerfile -t manorrock/persian:amd64-$VERSION .
        docker pull manorrock/persian:amd64-$VERSION
        export DOCKER_CLI_EXPERIMENTAL=enabled
        docker manifest create manorrock/persian:$VERSION \
           manorrock/persian:amd64-$VERSION
        docker manifest annotate manorrock/persian:$VERSION \
           manorrock/persian:amd64-$VERSION --os linux --arch amd64
        docker manifest push manorrock/persian:$VERSION
